# This is a comment line

FROM ubi8/ubi:8.3

LABEL description="This is a custom httpd container image"

MAINTAINER artur dietrich <artur@ovd.com.br>

LABEL description="A custom Apache container based on Ubi8"

RUN yum install -y httpd && yum clean all

RUN echo "Hello Artur" >/var/www/html/index.html

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]



